version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    container_name: mongodb
    restart: always
    mem_limit: 3.4GB
    ports:
      - "27017:27017"
    volumes:
      - '${PWD}/mongodb_data:/bitnami/mongodb' # sudo chown -R 1001 mongodb_data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

      # https://www.mongodb.com/docs/manual/reference/program/mongod/#synopsis
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=1
      - MONGODB_EXTRA_FLAGS=--wiredTigerCollectionBlockCompressor=zstd
      - MONGODB_EXTRA_FLAGS=--wiredTigerJournalCompressor=zstd
      - MONGODB_EXTRA_FLAGS=--wiredTigerDirectoryForIndexes
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ENABLE_JOURNAL=true

      # setting up replication
      # https://github.com/bitnami/containers/tree/main/bitnami/mongodb#setting-up-replication
      - MONGODB_REPLICA_SET_MODE=primary
      # - MONGODB_ADVERTISED_HOSTNAME=172.31.10.100
